version: '3.6'

services:
  users:
    container_name: users
    build: .
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
