"""empty message

Revision ID: b0fcda1b420f
Revises: bdde61bd5178
Create Date: 2019-06-11 08:59:28.020863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fcda1b420f'
down_revision = 'bdde61bd5178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'last_name')
    # ### end Alembic commands ###
