"""empty message

Revision ID: e003ef4d4cab
Revises: b0fcda1b420f
Create Date: 2019-06-11 09:01:55.430462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e003ef4d4cab'
down_revision = 'b0fcda1b420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'address')
    # ### end Alembic commands ###
